# Generated by Django 5.2.1 on 2025-05-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('extinct_since', models.IntegerField()),
                ('model', models.FileField(null=True, upload_to='model/')),
                ('super_power', models.CharField(
                    blank=True, default='', max_length=100)),
            ],
        ),
    ]
