# Generated by Django 5.2.1 on 2025-05-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalHologram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hologram_path', models.CharField(max_length=255)),
                ('hologram_size', models.CharField(max_length=50)),
                ('hologram_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('extinct_since', models.IntegerField()),
                ('hologram', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animals.animalhologram')),
            ],
        ),
    ]
