# Generated by Django 5.2.1 on 2025-05-21 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalhologram',
            name='hologram_color',
        ),
        migrations.RemoveField(
            model_name='animalhologram',
            name='hologram_path',
        ),
        migrations.RemoveField(
            model_name='animalhologram',
            name='hologram_size',
        ),
        migrations.AddField(
            model_name='animalhologram',
            name='file',
            field=models.FileField(null=True, upload_to='hologram/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='hologram',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.animalhologram'),
        ),
    ]
