# Generated by Django 5.2.1 on 2025-05-26 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='extinct_since',
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
