# Generated by Django 5.2.1 on 2025-05-26 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_extinct_since_alter_animal_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='extinct_since',
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(),
        ),
    ]
