# Generated by Django 5.2.1 on 2025-05-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_remove_animalhologram_hologram_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='hologram',
            field=models.FileField(null=True, upload_to='hologram/'),
        ),
        migrations.DeleteModel(
            name='AnimalHologram',
        ),
    ]
