# Generated by Django 5.2.1 on 2025-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_hologram_delete_animalhologram'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='super_power',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
